### ISSUE TITLE
Cuadro Comparativo de "características y estructura de textos"

### ISSUE THREAD

**Issue by Daniel-Velasco-Lopez** [SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-Daniel-Velasco-Lopez#1]
Daniel Velasco López Unidad 2-Cuadro Comparativo
[Cuadro Comparativo.pdf](https://github.com/SistemasTecTlaxiaco/actividad-5-cuadro-comparativo-de-textos-Daniel-Velasco-Lopez/files/9636821/Cuadro.Comparativo.pdf)

**Comment by YaelTrinidad** [comment]
ACT 5 CUADRO COMPARATIVO
 "CARACTERISTICAS Y ESTRUCTURAS DE LOS TEXTOS"
DEL 20% DE LA ACTIVIDAD, DADA LA RUBRICA OBTUVISTE EL  18%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
